### ISSUE TITLE
Not evaluate when there are declared and not used valiables

### ISSUE THREAD

**Issue by mkouhei** [mkouhei/gosh#4]
```
$ $GOPATH/bin/gosh
>>> i := 1
>>> fmt.Println("hello")
>>>
```

**Comment by mkouhei** [comment]
We can print the warning of "declared and not used".
Instead,  we will not be able to suppress when declare variable in omit main func.

**Comment by aerth** [comment]
a fix may be to use the _blank identifier_ whenever a new variable is defined.

`var x = 1` would become 
```
var x = 1
_ = x
```

`y := 2` (inside a function) would become
```
y := 2
_ = y
```
may get tricky with multiple variables, such as `var x, y, z := 1, 2, 3`
